pseudocode.md

feat:Added pseudocode file

---

db_schema/db_migration.sql

**Description:**
we were storing comments inside the task column of tasks_table, Now i have altered the tasks_table ,added new column for comments.This PR includes sql query to alter the table.
```sql
alter table tasks_table  
add column comments JSONB;
```

feat:updated db_migration.sql file

---

pseudocode.md

modified the pseudocode file

---

hrms_api_spec.yaml

File Name - hrms_api_specs.yaml

add new yaml file

---

hrms_api_spec.yaml

add new three api spects

---

hrms_api_spec.yaml

add new  api spects

---

hrms_api_spec.yaml

** modified hrms_api_spects **

modified hrms_api_spects

---

hrms_api_spec.yaml

** adding the getDesignation api specifications and add one more field in getEmployee api spects **

adding new getDesignation api spects

---

hrms_api_spec.yaml

Changes Made:
- Removed the `schema` section from the API specifications.
- Added an `example` directly in the API specifications to illustrate the expected response structure.

feat:modified api spects

---

hrms_pseudocode.md
workflow_admin_api_spec.yaml

1. Modified api specs in getProjectWorkflow api inside add one more  field the field name is  completed_usecases.
2. Add new file the file name is hrms_pseudocode.md

feat:modified api specs and add new file

---

hrms_api_spec.yaml

1. Adding new api specs the api name is employeeTracker.js

feat:adding new api specs

---

hrms_api_spec.yaml

1. Modified api specs the nams are signin,signup apis
2. Adding 3 new api specs the names are inviteUser, forgotPassword, resetPassword apis

feat:modified and add new api specs

---

db_schema/db_migration.sql

To make the name unique just altered the name column in the workflows_table

Altered workflow_table 

---

hrms_api_spec.yaml
hrms_pseudocode.md

1. Added a new API Specs
2. Added a new 4 apis pseudocode
3. Modified the pseudocode.md file

feat:modified api_spec and pseudocode

---

workflow_admin_api_spec.yaml

Added updateChecklist api specs in workflow_admin_api_spec.yaml file

feat:added workflow_admin_api_specs

---

workflow_admin_api_spec.yaml

1.Modified api specs
2. Adding getUsecaseTask.js api specs

feat:workflow_admin_api_spec.yaml

---

hrms_api_spec.yaml
workflow_admin_api_spec.yaml

1.Modified workflow api specs.
2. Modified hrms api specs and add 5 new api specs.

feat:modified api specs

---

hrms_pseudocode.md

1. Adding 6 api's  documentation in hrms_pseudocode.md file.

feat:adding api documentation in hrms pseudocode.md

---

workflow_admin_api_spec.yaml

Modified the workflow api specs the api name is getUsecaseTask.js.

feat:modified workflow api specs

---

db_schema/db_migration.sql

```sql
ALTER TABLE metadocs_table 
ALTER COLUMN doc_url TYPE VARCHAR(255);
```

updated sql script

---

db_schema/db_migration.sql

altered the table added org_id in the projects_table

altered the table added org_id in the projects_table

---

hrms_api_spec.yaml

1. Modified hrms api specs.
2. Correct the operationIds.

modified hrms api specs

---

pseudocode.md

1. Modified theworkflow pseudocode.
2. Write more effectively and easily understand the document.

feat: modified pseudocode.md file

---

hrms_api_spec.yaml
workflow_admin_api_spec.yaml

Made changes in workflow_api_specs and hrms_api_specs

Made changes in  api specs

---

db_schema/db_migration.sql

```sql
ALTER TABLE metadocs_table 
ADD COLUMN type VARCHAR(255);
ALTER TABLE document  
ADD COLUMN type VARCHAR(255);
```

updated db_migration.sql file

---

hrms_api_spec.yaml

Made Changes In hrms_api_specs

made changes in hrms_api_specs

---

workflow_admin_api_spec.yaml

Minor changes in workflow_api_specs

minor changes in workflow_api_specs

---

workflow_admin_api_spec.yaml

adding template.js,addTemplate.js api specs in the workflow_api_specs

adding two more api specs
